"use client";

import { useState } from "react";
import { headingFor } from "@/components/DerivationTree";
import type { FieldDerivation, SessionPayload } from "@/lib/api";

// Assembles a publication-ready LaTeX document from the kernel-verified
// results. This is pure formatting of expressions the kernel already verified;
// unverified results are deliberately left out and no physics runs here.

function buildPublicationLatex(
  action: SessionPayload["action"],
  verified: FieldDerivation[],
): string {
  const out: string[] = [
    "% Generated by Noether. Conventions: noether-default-v1.",
    "% Only kernel-verified results are included; edit freely.",
    "\\documentclass{article}",
    "\\usepackage{amsmath,amssymb}",
    "",
    "\\begin{document}",
    "",
    "\\section*{Action}",
    "\\begin{equation}",
    `  S = \\int ${action.measure_tex}\\,\\left(${action.lagrangian_tex ?? ""}\\right)`,
    "\\end{equation}",
    "",
  ];
  for (const d of verified) {
    const provenance = d.llm_name
      ? `${d.kernel_name} ${d.kernel_version}; script by ${d.llm_name} ${d.llm_version}`
      : `${d.kernel_name} ${d.kernel_version}`;
    out.push(`% ${headingFor(d)} (computed by ${provenance})`);
    out.push("\\begin{equation}");
    out.push(`  ${d.result_tex}`);
    out.push("\\end{equation}");
    out.push("");
  }
  out.push("\\end{document}");
  out.push("");
  return out.join("\n");
}

export default function ExportPanel({
  action,
  derivations,
  staleResultIds = [],
}: {
  action: SessionPayload["action"];
  derivations: FieldDerivation[];
  staleResultIds?: string[];
}) {
  const [copied, setCopied] = useState(false);
  const verified = derivations.filter(
    (d) => d.verified && d.result_tex && !staleResultIds.includes(d.result_id),
  );
  if (verified.length === 0) return null;

  const tex = buildPublicationLatex(action, verified);

  async function copy() {
    try {
      await navigator.clipboard.writeText(tex);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setCopied(false);
    }
  }

  function download() {
    const blob = new Blob([tex], { type: "text/x-tex" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = "noether-results.tex";
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="card">
      <h2>Publication LaTeX</h2>
      <p className="note">
        A clean LaTeX document of the {verified.length} kernel-verified result
        {verified.length === 1 ? "" : "s"} above. Unverified and stale results are
        left out. This only formats expressions the kernel already verified; no
        physics happens here.
      </p>
      <div className="derive-actions">
        <button onClick={copy}>{copied ? "Copied" : "Copy LaTeX"}</button>
        <button className="secondary" onClick={download}>
          Download .tex
        </button>
      </div>
      <textarea className="export-tex" readOnly value={tex} />
    </div>
  );
}
